"""initial schema

Revision ID: eae1e81b0cf9
Revises: 
Create Date: 2026-07-28 14:48:56.815160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eae1e81b0cf9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    if bind.engine.name == 'postgresql':
        bind.execute(sa.text("DROP TYPE IF EXISTS userrole CASCADE;"))
        bind.execute(sa.text("DROP TYPE IF EXISTS accountstatus CASCADE;"))
        bind.execute(sa.text("DROP TYPE IF EXISTS mediatype CASCADE;"))
        bind.execute(sa.text("DROP TYPE IF EXISTS priority CASCADE;"))
        bind.execute(sa.text("DROP TYPE IF EXISTS ticketstatus CASCADE;"))
        bind.execute(sa.text("DROP TYPE IF EXISTS costresponsibility CASCADE;"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apartments',
    sa.Column('unit_number', sa.String(length=50), nullable=False),
    sa.Column('building', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apartments_id'), 'apartments', ['id'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('resident', 'facility_employee', 'maintenance_staff', 'facility_manager', name='userrole'), nullable=False),
    sa.Column('avatar_color', sa.String(length=20), nullable=False),
    sa.Column('avatar_uri', sa.String(length=500), nullable=True),
    sa.Column('account_status', sa.Enum('active', 'pending', 'rejected', name='accountstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('apartment_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('specialization', sa.String(length=150), nullable=True),
    sa.Column('active_jobs', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('tickets',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('resident_id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=True),
    sa.Column('category_id', sa.String(length=50), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('media_type', sa.Enum('Image', 'Video', name='mediatype'), nullable=True),
    sa.Column('resident_note', sa.Text(), nullable=False),
    sa.Column('voice_note_url', sa.String(length=500), nullable=True),
    sa.Column('voice_note_duration_sec', sa.Integer(), nullable=True),
    sa.Column('ai_description', sa.Text(), nullable=False),
    sa.Column('ai_confidence', sa.Float(), nullable=False),
    sa.Column('priority', sa.Enum('Low', 'Medium', 'High', 'Critical', 'Emergency', name='priority'), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'Assigned', 'In_Progress', 'Resolved', 'Closed', name='ticketstatus'), nullable=False),
    sa.Column('cost_responsibility', sa.Enum('Owner', 'Resident', 'Society', 'Pending_Review', name='costresponsibility'), nullable=False),
    sa.Column('date_of_request', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_of_resolution', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_remarks', sa.Text(), nullable=True),
    sa.Column('resolution_proof_url', sa.String(length=500), nullable=True),
    sa.Column('resident_rating', sa.Integer(), nullable=True),
    sa.Column('resident_feedback', sa.Text(), nullable=True),
    sa.Column('is_overdue', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['resident_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=False)
    op.create_table('comments',
    sa.Column('ticket_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('ticket_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('ticket_history',
    sa.Column('ticket_id', sa.String(length=36), nullable=False),
    sa.Column('old_status', sa.Enum('Pending', 'Assigned', 'In_Progress', 'Resolved', 'Closed', name='ticketstatus'), nullable=True),
    sa.Column('new_status', sa.Enum('Pending', 'Assigned', 'In_Progress', 'Resolved', 'Closed', name='ticketstatus'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_history_id'), 'ticket_history', ['id'], unique=False)
    op.create_table('ticket_media',
    sa.Column('ticket_id', sa.String(length=36), nullable=False),
    sa.Column('media_url', sa.String(length=500), nullable=False),
    sa.Column('media_type', sa.Enum('Image', 'Video', name='mediatype'), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_media_id'), 'ticket_media', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_media_id'), table_name='ticket_media')
    op.drop_table('ticket_media')
    op.drop_index(op.f('ix_ticket_history_id'), table_name='ticket_history')
    op.drop_table('ticket_history')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('categories')
    op.drop_index(op.f('ix_apartments_id'), table_name='apartments')
    op.drop_table('apartments')
    
    bind = op.get_bind()
    if bind.engine.name == 'postgresql':
        bind.execute(sa.text("DROP TYPE IF EXISTS userrole CASCADE;"))
        bind.execute(sa.text("DROP TYPE IF EXISTS accountstatus CASCADE;"))
        bind.execute(sa.text("DROP TYPE IF EXISTS mediatype CASCADE;"))
        bind.execute(sa.text("DROP TYPE IF EXISTS priority CASCADE;"))
        bind.execute(sa.text("DROP TYPE IF EXISTS ticketstatus CASCADE;"))
        bind.execute(sa.text("DROP TYPE IF EXISTS costresponsibility CASCADE;"))
    # ### end Alembic commands ###
